"Classification models for the McScript dataset."
from models.advanced_attention_bert import AdvancedAttentionBertClassifier
from models.advanced_bert import AdvancedBertClassifier
from models.attentive_reader import AttentiveReader
from models.baseline import BaselineClassifier
from models.dcmn import Dcmn
from models.hierarchical_attention_network import HierarchicalAttentionNetwork
from models.hierarchical_bert import HierarchicalBert
from models.relational_han import RelationalHan
from models.relational_transformer_model import RelationalTransformerModel
from models.simple_bert import SimpleBertClassifier
from models.simple_trian import SimpleTrian
from models.trian import Trian
